openapi: 3.0.3
info:
  title: Todo Chatbot Task API
  description: API for managing tasks in the cloud-native todo chatbot system
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://api.todo-chatbot.example.com
    description: Production server

paths:
  /tasks:
    get:
      summary: Get user's tasks
      description: Retrieve all tasks for the authenticated user
      parameters:
        - name: status
          in: query
          description: Filter tasks by status
          schema:
            type: string
            enum: [pending, completed, in-progress]
        - name: limit
          in: query
          description: Limit number of results
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: offset
          in: query
          description: Offset for pagination
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: Successful response with list of tasks
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
                  total:
                    type: integer
                  offset:
                    type: integer
        '401':
          description: Unauthorized - invalid or missing token
        '500':
          description: Internal server error

    post:
      summary: Create a new task
      description: Create a new task using natural language input
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
                  description: Task title or natural language description
                  example: "Buy groceries tomorrow at 3pm"
                description:
                  type: string
                  description: Optional detailed description
                due_date:
                  type: string
                  format: date-time
                  description: Optional due date
                priority:
                  type: string
                  enum: [low, medium, high, critical]
                  default: medium
                tags:
                  type: array
                  items:
                    type: string
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid request data
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /tasks/{id}:
    get:
      summary: Get a specific task
      description: Retrieve details of a specific task by ID
      parameters:
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

    put:
      summary: Update a task
      description: Update properties of an existing task
      parameters:
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid request data
        '404':
          description: Task not found
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

    delete:
      summary: Delete a task
      description: Permanently delete a task
      parameters:
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
      responses:
        '204':
          description: Task deleted successfully
        '404':
          description: Task not found
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /tasks/{id}/complete:
    post:
      summary: Mark task as complete
      description: Mark a task as completed
      parameters:
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
      responses:
        '200':
          description: Task marked as complete
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /chat:
    post:
      summary: Send message to chatbot
      description: Process natural language input and perform actions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
              properties:
                message:
                  type: string
                  description: User's message to the chatbot
                context:
                  type: string
                  description: Conversation context identifier
      responses:
        '200':
          description: Chatbot response with actions performed
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: Chatbot's natural language response
                  actions:
                    type: array
                    description: List of actions performed
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          description: Type of action performed
                        result:
                          type: object
                          description: Result of the action
        '400':
          description: Invalid message format
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /reminders:
    post:
      summary: Schedule a reminder
      description: Schedule a reminder for a task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - task_id
                - scheduled_time
              properties:
                task_id:
                  type: string
                  description: ID of the task to remind about
                scheduled_time:
                  type: string
                  format: date-time
                  description: When to send the reminder
                method:
                  type: string
                  enum: [email, push, sms, in-app]
                  default: in-app
      responses:
        '201':
          description: Reminder scheduled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reminder'
        '400':
          description: Invalid request data
        '404':
          description: Task not found
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          description: Unique task identifier
        title:
          type: string
          description: Task title
        description:
          type: string
          description: Optional detailed description
        status:
          type: string
          enum: [pending, completed, in-progress]
          description: Current status of the task
        priority:
          type: string
          enum: [low, medium, high, critical]
          description: Priority level of the task
        due_date:
          type: string
          format: date-time
          description: Optional due date
        created_at:
          type: string
          format: date-time
          description: Timestamp of creation
        updated_at:
          type: string
          format: date-time
          description: Timestamp of last update
        user_id:
          type: string
          description: ID of the user who owns the task
        tags:
          type: array
          items:
            type: string
          description: Tags for categorizing the task

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          description: Updated task title
        description:
          type: string
          description: Updated detailed description
        status:
          type: string
          enum: [pending, completed, in-progress]
          description: Updated status of the task
        priority:
          type: string
          enum: [low, medium, high, critical]
          description: Updated priority level
        due_date:
          type: string
          format: date-time
          description: Updated due date

    Reminder:
      type: object
      properties:
        id:
          type: string
          description: Unique reminder identifier
        task_id:
          type: string
          description: ID of the associated task
        user_id:
          type: string
          description: ID of the user receiving the reminder
        scheduled_time:
          type: string
          format: date-time
          description: When the reminder is scheduled for
        status:
          type: string
          enum: [scheduled, sent, cancelled]
          description: Current status of the reminder
        method:
          type: string
          enum: [email, push, sms, in-app]
          description: Method of delivery for the reminder
        created_at:
          type: string
          format: date-time
          description: Timestamp of creation
        sent_at:
          type: string
          format: date-time
          description: Timestamp when reminder was sent (if sent)

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT